repos:
  - repo: https://github.com/Yelp/detect-secrets
    # v.1.5.0
    rev: 01886c8a910c64595c47f186ca1ffc0b77fa5458  # pragma: allowlist secret
    hooks:
      - id: detect-secrets
        # If you need to change this, be sure to update .circleci/config.yml as well
        exclude: package-lock.json|Pipfile.lock|.bandit-baseline.json|.secrets.yaml|app_api_schema.yaml

