
name: Secrets detection using detect-secrets
on:
  pull_request:
    branches: [ "main" ]
jobs:
  secrets-detect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Install detect-secrets
        run: pip install -r <(echo "detect-secrets==1.5.0 --hash=sha256:6bb46dcc553c10df51475641bb30fd69d25645cc12339e46c824c1e0c388898a"  # pragma: allowlist secret
      - name: Run detect secrets.
        run: git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }} |  xargs detect-secrets-hook

