
name: Static analysis using semgrep
on:
  pull_request:
    branches: [ "main" ]
jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          fetch-depth: 0
      - name: Install semgrep
        run: pip install semgrep
      - name: Run semgrep
        run: semgrep --config auto --error

